package exe.weazy.intents.util

const val DEFAULT_PAGE_SIZE = 20
const val DEFAULT_PREFETCH_DISTANCE = 10

const val MARK_UP_ACTIVITY_REQUEST_CODE = 101
const val CATEGORIES_ACTIVITY_REQUEST_CODE = 102

const val SUCCESS_RESULT_CODE = 200
const val ERROR_RESULT_CODE = 201